<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_menuOption</name>
   <tag></tag>
   <elementGuidId>184a6cb8-2a92-4f1f-b528-a725753406ac</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuOption</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;peopleInMenu&quot;)/div[@class=&quot;personInMenu&quot;]/div[@class=&quot;studentContent&quot;]/div[@class=&quot;menuOptions&quot;]/a[1]/div[@class=&quot;menuOption&quot;]</value>
   </webElementProperties>
</WebElementEntity>
