<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SupportJamieGA</name>
   <tag></tag>
   <elementGuidId>69dc0409-d0fc-4080-b6a7-8ca0a4473527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[count(. | id(&quot;logoutForm&quot;)/div[1]) = count(id(&quot;logoutForm&quot;)/div[1])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                SupportJamieGA
                
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logoutForm&quot;)/div[1]</value>
   </webElementProperties>
</WebElementEntity>
