<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Clubs</name>
   <tag></tag>
   <elementGuidId>6511de3f-e28b-4179-8c66-39a8e2530650</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clubs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;is-open&quot;]/app-container[@class=&quot;app-container&quot;]/main[@class=&quot;main-container u-direction-row&quot;]/nav[@class=&quot;is-open&quot;]/div[@class=&quot;icon-menu&quot;]/ul[1]/a[2]/li[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
