<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__720kb-datepicker-calendar-m</name>
   <tag></tag>
   <elementGuidId>b966da63-47e5-4d1a-94ba-f638102ae3a4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_720kb-datepicker-calendar-month-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'_720kb-datepicker-item-hidden': !willNextMonthBeSelectable()}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>nextMonth()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-container[@class=&quot;app-container&quot;]/main[@class=&quot;main-container u-direction-row&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;u-direction-row flex&quot;]/main[@class=&quot;content no-item-drawer flex&quot;]/div[@class=&quot;content-area  with-action-drawer&quot;]/div[@class=&quot;u-overflow-hidden u-direction-row u-full-height flex&quot;]/div[@class=&quot;u-flex-stretch u-overflow-y-auto scroll-spy-scroller&quot;]/div[@class=&quot;content-main&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-required-if ng-valid-is-date ng-valid-greater-than-or-equal-to-date ng-valid-multiple-instalments ng-valid-number ng-valid-less-than-or-equal-to-date ng-valid-minimum-amount-for-consent ng-valid-minimum-amount ng-dirty ng-valid-parse&quot;]/div[@class=&quot;page payment-details active&quot;]/div[@class=&quot;page-content&quot;]/table[@class=&quot;u-full-width&quot;]/tbody[1]/tr[5]/td[3]/div[@class=&quot;u-direction-row visible-to flex&quot;]/datepicker[@class=&quot;center-in-row calendar-fly-in-from-right&quot;]/div[@class=&quot;date-picker-input-holder&quot;]/label[@class=&quot;with-icon&quot;]/div[@class=&quot;_720kb-datepicker-calendar _720kb-datepicker-open&quot;]/div[@class=&quot;_720kb-datepicker-calendar-header&quot;]/div[@class=&quot;_720kb-datepicker-calendar-header-right&quot;]/a[@class=&quot;_720kb-datepicker-calendar-month-button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
