<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Flexible amount can be pai</name>
   <tag></tag>
   <elementGuidId>b0c50598-c57f-4b26-a6a8-18a391936ff8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>ctrl.onSelect(option.value)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flexible amount: can be paid more than once</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-container[@class=&quot;app-container&quot;]/main[@class=&quot;main-container u-direction-row&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;u-direction-row flex&quot;]/main[@class=&quot;content no-item-drawer flex&quot;]/div[@class=&quot;content-area  with-action-drawer&quot;]/div[@class=&quot;u-overflow-hidden u-direction-row u-full-height flex&quot;]/div[@class=&quot;u-flex-stretch u-overflow-y-auto scroll-spy-scroller&quot;]/div[@class=&quot;content-main&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-required-if ng-valid-is-date ng-valid-greater-than-or-equal-to-date ng-valid-multiple-instalments ng-valid-number ng-valid-greater-than-or-equal-to-places-taken ng-valid-less-than-or-equal-to-date ng-valid-minimum-amount-for-consent ng-valid-minimum-amount ng-dirty ng-valid-parse&quot;]/div[@class=&quot;page payment-details active&quot;]/div[@class=&quot;page-content&quot;]/table[@class=&quot;u-full-width&quot;]/tbody[1]/tr[2]/td[2]/drop-down[@class=&quot;drop-down u-full-width ng-invalid&quot;]/div[@class=&quot;drop-down-children&quot;]/div[@class=&quot;drop-down-option&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
