<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Instalments0.DueDate</name>
   <tag></tag>
   <elementGuidId>b0aaa94d-31b1-4fd8-a600-5e32a9b636d6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Instalments[0].DueDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inst.date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-date-picker ng-untouched ng-valid-less-than-or-equal-to-date ng-dirty ng-valid-parse ng-valid-required ng-invalid ng-invalid-is-date ng-invalid-greater-than-or-equal-to-date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>greater-than-or-equal-to-date</name>
      <type>Main</type>
      <value>model.visibleFrom</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>less-than-or-equal-to-date</name>
      <type>Main</type>
      <value>model.visibleTo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-container[@class=&quot;app-container&quot;]/main[@class=&quot;main-container u-direction-row&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;u-direction-row flex&quot;]/main[@class=&quot;content no-item-drawer flex&quot;]/div[@class=&quot;content-area  with-action-drawer&quot;]/div[@class=&quot;u-overflow-hidden u-direction-row u-full-height flex&quot;]/div[@class=&quot;u-flex-stretch u-overflow-y-auto scroll-spy-scroller&quot;]/div[@class=&quot;content-main&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-required-if ng-valid-multiple-instalments ng-valid-number ng-valid-less-than-or-equal-to-date ng-valid-minimum-amount-for-consent ng-valid-minimum-amount ng-dirty ng-valid-parse ng-invalid-is-date ng-invalid-greater-than-or-equal-to-date&quot;]/div[@class=&quot;page costs-instalments&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;instalments-holder&quot;]/div[1]/table[@class=&quot;default&quot;]/tbody[@class=&quot;ng-untouched ng-valid-multiple-instalments ng-invalid ng-invalid-required ng-valid-less-than-or-equal-to-date ng-valid-minimum-amount-for-consent ng-valid-minimum-amount ng-valid-number ng-dirty ng-valid-parse ng-invalid-is-date ng-invalid-greater-than-or-equal-to-date&quot;]/tr[1]/td[2]/datepicker[@class=&quot;center-in-row&quot;]/div[@class=&quot;date-picker-input-holder&quot;]/label[@class=&quot;with-icon&quot;]/input[@class=&quot;input-date-picker ng-untouched ng-valid-less-than-or-equal-to-date ng-dirty ng-valid-parse ng-valid-required ng-invalid ng-invalid-is-date ng-invalid-greater-than-or-equal-to-date&quot;]</value>
   </webElementProperties>
</WebElementEntity>
