<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Instalments0.AmountForma</name>
   <tag></tag>
   <elementGuidId>b5f48001-9a39-4081-8810-9634175b317f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Instalments[0].AmountFormatted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>apply-filter</name>
      <type>Main</type>
      <value>currencyFormat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inst.amountFormatted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>ctrl.amountIsReadOnly(inst, true, false)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid-minimum-amount-for-consent ng-valid-number ng-dirty ng-valid-parse ng-valid-required ng-invalid ng-invalid-minimum-amount</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-container[@class=&quot;app-container&quot;]/main[@class=&quot;main-container u-direction-row&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;u-direction-row flex&quot;]/main[@class=&quot;content no-item-drawer flex&quot;]/div[@class=&quot;content-area  with-action-drawer&quot;]/div[@class=&quot;u-overflow-hidden u-direction-row u-full-height flex&quot;]/div[@class=&quot;u-flex-stretch u-overflow-y-auto scroll-spy-scroller&quot;]/div[@class=&quot;content-main&quot;]/form[@class=&quot;ng-invalid ng-valid-maxlength ng-valid-required-if ng-valid-multiple-instalments ng-valid-number ng-valid-less-than-or-equal-to-date ng-valid-minimum-amount-for-consent ng-dirty ng-valid-parse ng-invalid-is-date ng-valid-greater-than-or-equal-to-date ng-valid-required ng-invalid-minimum-amount&quot;]/div[@class=&quot;page costs-instalments&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;instalments-holder&quot;]/div[1]/table[@class=&quot;default&quot;]/tbody[@class=&quot;ng-untouched ng-valid-multiple-instalments ng-invalid ng-valid-less-than-or-equal-to-date ng-valid-minimum-amount-for-consent ng-valid-number ng-dirty ng-valid-parse ng-invalid-is-date ng-valid-greater-than-or-equal-to-date ng-valid-required ng-invalid-minimum-amount&quot;]/tr[1]/td[3]/div[@class=&quot;instalment-amount-field&quot;]/div[1]/label[@class=&quot;with-icon&quot;]/input[@class=&quot;ng-untouched ng-valid-minimum-amount-for-consent ng-valid-number ng-dirty ng-valid-parse ng-valid-required ng-invalid ng-invalid-minimum-amount&quot;]</value>
   </webElementProperties>
</WebElementEntity>
